### ISSUE TITLE
setName doesn't work for attribute

### ISSUE THREAD

**Issue by strange-v** [Respect/Validation#620]
Hi guys.
I have some troubles with setName and attributes.
My code looks like this:
```php
$validator = v::attribute('email', v::notEmpty()->email())->setName('Email Field')
	->attribute('password', v::notEmpty()->noWhitespace())->setName('Password Field');
$this->validator->assert($entity);

$errors = $ex->findMessages([
    'email' => 'Error: {{name}}',
    'notEmpty' => 'Error: {{name}}',
    'noWhitespace' => 'Error: {{name}}'
]);
```
I've expected to see error
> Error: Email Field
> Error: Password Field

But I've got
> Error: email
> Error: password

Why so? How I can set name for attribute correctly?
Thank you.

**Comment by henriquemoody** [comment]
Thanks for reporting, seem it's really a bug.

Although, you're using `setName()` incorrectly, because you're defining the name of the _chain_ two times, what you really want to do it:

```php
v::attribute('email', v::notEmpty()->email()->setName('Email Field'))
    ->attribute('password', v::notEmpty()->noWhitespace()->setName('Password Field'))
    ->assert($entity);
```

I will take a closer look to this bug as soon as possible.

**Comment by francoism90** [comment]
This still doesn't work:
```
$user = new \stdClass;
$user->email = 'Ale@@@xandre';
$user->password = 'Ale@@@xandre';

$username = v::attribute('email', v::notEmpty()->email()->setName('Email Field'))
    ->attribute('password', v::notEmpty()->noWhitespace()->setName('Password Field'))
    ->assert($user);`
```

Result:
`Array ( [0] => email must be valid email )`

Thanks. :)

**Comment by henriquemoody** [comment]
Oh, I got it. I will fix it as soon as possible.

**Comment by batusa** [comment]
Should the proper behavior be the name of the chain of rules for `attribute`, change `attribute`'s name?

I was thinking about something like `KeySet` but for attributes, it would be something like:

```php
v::attributeSet(
    v::attribute('email', v::notEmpty()->email())->setName('Email Field'),
    v::attribute('password', v::notEmpty()->noWhitespace())->setName('Password Field')
)->assert($entity);
```

I don't know if I took it too far...

What do you think?

**Comment by henriquemoody** [comment]
Unfortunately the `AttributeSet` rule won't fix the problem, but it's a nice idea. Can you create a issue for that, @batusa?

**Comment by henriquemoody** [comment]
I fixed part of the problem, but when using `findMessages()` there are a few errors. See #675.

@francoism90 and @strange-v, have you tried the `getMessages()` method?

**Comment by francoism90** [comment]
@henriquemoody Thanks for the fix! Haven't found time to test.. will try asap. :)

**Comment by mscreenie** [comment]
Is this fixed?

**Comment by bs-thomas** [comment]
It seems like it's still not working, thought I'm using "key" (from an array) instead of "attributes" (from an object)

**Comment by mscreenie** [comment]
Yes. Im stuck with the same problem, there haven't been any updates either since I opened an separate issue regarding this. 

My project is almost finished and validation is still on my to do list. I'll probably end up writing my own to handle validation just so I can complete it on time.

**Comment by bs-thomas** [comment]
@mscreenie I'm just at the point of deciding to use this library or not.  Seems like their last commit on 1 Jul.  Not so long ago, but not so recent either.

I'm on Laravel and I didn't want to use their dependant validation library in case I want to do a framework switch.  But since this is such a core problem, guess I'd have to seek for other alternatives such as Valitron or just stick with Laravel's original validator.

@mscreenie Though it's kinda out of topic, have you found any other good PHP validation libraries?

**Comment by mscreenie** [comment]
@bs-thomas I had considered Laravel or Symphony but haven't done so for similar reasons to yours.

Looking at Valitron - last I tried it came with some caveats with nested array validation involving forms and a few others I can't recall. Previously used Sirius, syntax was a little strange but it worked well. I tried switching back however the latest version is unusable. 

I've read some Laravels docs and it seems a good solution if you can accept framework lock in. 

There is another issue related to findMessages and keyNested if you are planning on doing anything useful with nested arrays and forms. https://github.com/Respect/Validation/issues/689

**Comment by henriquemoody** [comment]
Hey guys,

The past months I had no much time to spent on this library and as you can see there are no much contributors but me working on it. I moved to another country, got a new job and I'm still getting used to my new routine.

I don't know when I will have time to spend all necessary amount of hours to fix all problems we have, so I would really appreciate your help through pull requests.

About this one, I was expecting some feedback on #675 but I saw none so far.

**Comment by mscreenie** [comment]
@henriquemoody  Thanks for explaining , glad to hear you've started a new job. Kinda in the same position myself of getting used to a new routine.

**Comment by henriquemoody** [comment]
This bug was finally fixed on versions [1.0.11](https://packagist.org/packages/respect/validation#1.0.11) and [1.1.6](https://packagist.org/packages/respect/validation#1.1.6) by #675.

I'm very sorry about my delay (I talked about that already https://github.com/Respect/Validation/issues/620#issuecomment-237474435).

Thanks for reporting! :panda_face:
